// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiaRd8VZxa3PHZYGWQcj3bGxfglGG-Pac',
    appId: '1:18714329684:web:b34224b815c4a345ca63c1',
    messagingSenderId: '18714329684',
    projectId: 'flutter-app-efdb4',
    authDomain: 'flutter-app-efdb4.firebaseapp.com',
    storageBucket: 'flutter-app-efdb4.firebasestorage.app',
    measurementId: 'G-WSCJJM1B6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXH2Uusdcs0U9_oearRg3V7UB2LzsND8c',
    appId: '1:18714329684:android:f66404a03d92d4fdca63c1',
    messagingSenderId: '18714329684',
    projectId: 'flutter-app-efdb4',
    storageBucket: 'flutter-app-efdb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6ZoLTmrkXrmTlbiRxXMcRuwnxHgzMck',
    appId: '1:18714329684:ios:9efe4bea8e2f5964ca63c1',
    messagingSenderId: '18714329684',
    projectId: 'flutter-app-efdb4',
    storageBucket: 'flutter-app-efdb4.firebasestorage.app',
    androidClientId: '18714329684-fjfh2cicvjvk7de4cs3nlbdbi2aoi4n3.apps.googleusercontent.com',
    iosClientId: '18714329684-8nmb82al9osevnl64rjikn8bva2ptn8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6ZoLTmrkXrmTlbiRxXMcRuwnxHgzMck',
    appId: '1:18714329684:ios:9efe4bea8e2f5964ca63c1',
    messagingSenderId: '18714329684',
    projectId: 'flutter-app-efdb4',
    storageBucket: 'flutter-app-efdb4.firebasestorage.app',
    androidClientId: '18714329684-fjfh2cicvjvk7de4cs3nlbdbi2aoi4n3.apps.googleusercontent.com',
    iosClientId: '18714329684-8nmb82al9osevnl64rjikn8bva2ptn8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiaRd8VZxa3PHZYGWQcj3bGxfglGG-Pac',
    appId: '1:18714329684:web:7c017e93d669afa3ca63c1',
    messagingSenderId: '18714329684',
    projectId: 'flutter-app-efdb4',
    authDomain: 'flutter-app-efdb4.firebaseapp.com',
    storageBucket: 'flutter-app-efdb4.firebasestorage.app',
    measurementId: 'G-6RNN728KTZ',
  );
}
